### PR TITLE
Feature/on popup event

### PR DESCRIPTION
**Pull request by StrangeWill**
Also includes #19 (not really possible to cleanly merge to minified files being included).

Adds the ability to configure an "onPopup" event that is configurable via the options.

### CODE REVIEW

**Comment by beeker1121** [comment]
Sorry for taking so long to merge, thank you for coding this!

**Comment by StrangeWill** [comment]
No problem, I know what that's like, I should make another one that updates the docs because I'm a jerk and didn't do that...

**Comment by beeker1121** [comment]
If you want to add the onPopup feature to the options there, that would be awesome.  I'll merge once you post.

**Comment by StrangeWill** [comment]
Sure, I'll do that tomorrow.

**Pull request merged**
